trigger: none 
jobs:
- job: BuildModules
  strategy: 
    parallel: 1
  pool:
    vmImage: windows-2019
  variables:
    - group: keys
  steps:
  - checkout: self
  # - task: CacheBeta@0
  #   inputs:
  #     key: paket8 | paket.lock
  #     path: $(Pipeline.Workspace)/.nuget/packages
  #   displayName: Cache NuGet packages
  - task: PowerShell@2
    displayName: Build
    inputs:
      targetType: inline
      script: |
        Write-Verbose
      pwsh: true
      errorActionPreference: continue
      failOnStderr: false
      ignoreLASTEXITCODE: true
  