trigger: none 
jobs:
- job: BuildModules
  strategy: 
    parallel: 1
  pool:
    vmImage: windows-2019
  variables:
    - group: keys
  steps:
  - checkout: self
  # - task: CacheBeta@0
  #   inputs:
  #     key: paket8 | paket.lock
  #     path: $(Pipeline.Workspace)/.nuget/packages
  #   displayName: Cache NuGet packages
  - task: PowerShell@2
    displayName: Build
    inputs:
      targetType: inline
      script: |
        ##vso[task.logdetail id=new guid;name=project1;type=build;order=1]create new timeline record

        $VerbosPreference="continue"
        Install-Module XpandPwsh
        Write-Verbose aaa
      
      errorActionPreference: stop
      failOnStderr: false
      ignoreLASTEXITCODE: true
  